### ISSUE TITLE
Conflict with stylus package

### ISSUE THREAD

**Issue by popaprozac** [mattkrick/meteorTooltips#1]
`While selecting package versions:
    error: Conflict: Constraint stylus@1.0.6 is not satisfied by stylus 2.511.1.
    Constraints on package "stylus":
    * stylus@=2.511.1 <- top level
    * stylus@1.0.6 <- mattkrick:tooltips 0.0.1`

**Comment by mattkrick** [comment]
yeah, they totally redid that stuff in v1.1, added deprecated tag.

**Comment by popaprozac** [comment]
Thanks for the quick response 👍🏻
